### ISSUE TITLE
Update lab webpage

### ISSUE THREAD

**Issue by jmshapir** [gslab-econ/gslab-econ.github.io#1]
Please update the [lab webpage](http://gslab-econ.github.io/) to reflect arrivals/departures. You can keep this issue open until all the transitions are done.

Note that this repository is public so we should not discuss other lab business in issue comments and commit messages here.

**Comment by arosenbe** [comment]
@jmshapir, I've updated Jiwon's information for the "Past members" and added myself to the "Current Research Professionals." Should I add Frank as well?

**Comment by jmshapir** [comment]
No need for that, thanks.

**Comment by arosenbe** [comment]
The webpage is current through @M-R-Sullivan. I'm leaving the issue open until Chuan arrived in August.

**Comment by jmshapir** [comment]
@arosenbe let's add @ashahidinejad to past members

bye @ashahidinejad! keep in touch...

**Comment by arosenbe** [comment]
It's official now @ashahidinejad

**Comment by ashahidinejad** [comment]
Thanks you :)

**Comment by arosenbe** [comment]
Updating lab webpage to include @stanfordquan.

**Comment by arosenbe** [comment]
I've updated the lab webpage through the transitions, closing task.
