### ISSUE TITLE
Update info for Pat DeJarnette on lab website

### ISSUE THREAD

**Issue by jmshapir** [gslab-econ/gslab-econ.github.io#2]
Let's update the [lab site](http://gslab-econ.github.io/) with info for [Pat DeJarnette](http://www.patdejar.net/). 

I am assigning to the whole gang and whoever has some time can grab this.

**Comment by jmshapir** [comment]
Looks like we can also update [Nathan Petek](https://sites.google.com/site/nathanpetek/)

**Comment by M-R-Sullivan** [comment]
@jmshapir - I just made those updates, and will close this now (from #1 I take it that PR isn't necessary here).

Summary: updated the lab webpage to [this commit](https://github.com/gslab-econ/gslab-econ.github.io/blob/3cc11f08fc6def983bb109477734c6f0bc3bc240/index.html) with Pat DeJarnette's  and Natan Petek's titles and websites as of Dec. 21, 2016.

**Comment by jmshapir** [comment]
Thanks @M-R-Sullivan.  No need for peer review. Small detail: for completed PhDs we should replace the range with the year, so Petek's "2011-2016" becomes "2016" and likewise for DeJarnette.

**Comment by M-R-Sullivan** [comment]
Right - I've made the change, @jmshapir. Closing again now.
