### ISSUE TITLE
Update status of Adam Rosenberg

### ISSUE THREAD

**Issue by mengsongouyang** [gslab-econ/gslab-econ.github.io#8]
Update the lab public GitHub page to move Adam to the "past members".

**Comment by mengsongouyang** [comment]
@jmshapir, Following the [comment](https://github.com/gslab-econ/admin/issues/151#issuecomment-417747840) in my intake issue, sadly, I moved @arosenbe  to the "Past Members" on the [lab page](http://gslab-econ.github.io).

<img width="473" alt="quan and adam on lab page" src="https://user-images.githubusercontent.com/39852362/45004565-a86bcd00-afa2-11e8-85d5-7f5327dae697.png">

FYI, I used Adam's gmail address as the link. Please let me know if any other link is more suitable.

**Comment by jmshapir** [comment]
Looks good @mengsongouyang, thanks!

**Comment by mengsongouyang** [comment]
Brief Summary:

- Updated the lab page to move Adam to the "Past Members" and used Adam's gmail as the link.
