### ISSUE TITLE
Update lab webpage

### ISSUE THREAD

**Issue by mengsongouyang** [gslab-econ/gslab-econ.github.io#9]
The goal of this task is to update our [lab webpage](http://gslab-econ.github.io).

We should update @mollywharton, @Shun-Yang and @arosenbe's information.

Ideally, we also want to update the status of other past members. So far as I know, [Ernest Liu](https://scholar.princeton.edu/ernestliu/home) is Assistant Professor at Princeton now, and [Linh Tô](https://www.linhto.com) is Assistant Professor at Boston University.

@mollywharton, Could you please take over this task? Some useful previous issues in this repo and also [here](https://github.com/gslab-econ/admin/issues/149).

@jmshapir @DavidRitzwoller  FYI

**Comment by mengsongouyang** [comment]
And Charles Hodgson moving to Yale.

**Comment by gentzkow** [comment]
And Nick Tsivanidis Asst Prof at Hass / Berkeley Eco

>

**Comment by mollywharton** [comment]
@mengsongouyang I've modified the page with the following updates:

- Added myself to the roster of current members (though I do not yet have a page on the SIEPR website so just linked to my email—will have to add the link once they update the website)
- Updated @Shun-Yang and @arosenbe's info
- Updated the status of other past members with the changes you and @gentzkow mentioned, and also made sure all of the other info and links are up to date

**Comment by mengsongouyang** [comment]
Thanks @mollywharton! All looks perfect to me. 👍 Feel free to close this issue.

**Comment by jmshapir** [comment]
@mollywharton while we're touching this can we revise my title from "George S. and Nancy B. Parker Professor of Economics" to just "Professor of Economics"? (I have yet a different title now but this seems simpler than maintaining it.)

Thanks!

**Comment by mollywharton** [comment]
@jmshapir yep, all set!

**Comment by jmshapir** [comment]
Thank you!
